version: 2.1
orbs:
  node: circleci/node@2.0.1

# executors:
#   executor1:
#     docker:
#       - image: node/default
#     working_directory: /env1
#   executor2:
#     docker:
#       - image: node/default
#     working_directory: /env2

jobs:
  # install-node-example:
  #   docker:
  #     - image: 'cimg/base:stable'
  #   steps:
  #     - checkout
  #     - node/install:
  #         install-yarn: true
  #         node-version: latest
  #     - run: node --version
  build1:
    executor:
      name: node/default
    steps:
      - checkout
      - run:
          name: See [~/project] Dir
          command: ls
      - run:
          name: See env1 Dir
          command: cd ./env1 && ls
      - node/install-packages:
          with-cache: true
          app-dir: ./env1
      # - run:
      #     name: Run npm in env1
      #     command: cd ~/project/env1 && npm run start
  build2:
    executor:
      name: node/default
    steps:
      - checkout
      - run:
          name: See [~/project] Dir
          command: ls
      - run:
          name: See env2 Dir
          command: cd ~/project/env2 && ls
      - node/install-packages:
          with-cache: true
          app-dir: ~/project/env2
      - run:
          name: Run npm in env2
          command: cd ~/project/env2 && npm run start
workflows:
    buildAll:
      jobs:
        # - install-node-example
        - build1
        - build2