version: 2.1
orbs:
  node: circleci/node@2.0.1

# executors:
#   executor1:
#     docker:
#       - image: node/default
#     working_directory: /env1
#   executor2:
#     docker:
#       - image: node/default
#     working_directory: /env2

jobs:
  # install-node-example:
  #   docker:
  #     - image: 'cimg/base:stable'
  #   steps:
  #     - checkout
  #     - node/install:
  #         install-yarn: true
  #         node-version: latest
  #     - run: node --version
  build1:
    executor:
      name: node/default
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: test1_0
          command: ls
      - run:
          name: test1_1
          command: cd ~/project/env1 && ls
      # - run:
      #     name: test1_2
      #     command: ls
      # - node/install-packages:
      #     with-cache: true
      #     app-dir: /env1
      # - node/install-packages:
      #     with-cache: true
      #     app-dir: /circle_ci/env1
      # - run: cd /circle_ci/env1
      # - run: npm run start
  build2:
    executor:
      name: node/default
    steps:
      - checkout
      - run:
          name: test2_0
          command: ls
      # - run:
      #     name: test2_1
      #     command: cd /env2 && ls
      - node/install-packages:
          with-cache: true
          app-dir: ~/project/env2
      # - node/install-packages:
      #     with-cache: true
      #     app-dir: /circle_ci/env2
      # - run: cd /circle_ci/env2
      # - run: npm run start
workflows:
    buildAll:
      jobs:
        # - install-node-example
        - build1
        - build2